FLOW_NAME=bulk-import-git-repos Serverless Workflow
FLOW_SUMMARY=bulk-import-git-repos Serverless Workflow
FLOW_DESCRIPTION=Workflow for creating pull requests (GitHub) or merge requests (GitLab) based on approvalTool parameter
