openapi: 3.0.0
info:
  title: Azure API
  version: v1beta1
paths:
  /v1.0/me:
    get:
      description: get profile
      operationId: getProfile
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "401":
          description: Unauthorized
      security:
        - BearerToken: []
components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      description: Bearer Token authentication
