apiVersion: v1
data:
  application.properties: |
    quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL}
    quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}
    quarkus.rest-client.mtv_yaml.url=${OCP_API_SERVER_URL}
    quarkus.openapi-generator.mtv_yaml.auth.BearerToken.bearer-token=${OCP_API_SERVER_TOKEN}
    quarkus.tls.trust-all=true
    quarkus.kubernetes-client.trust-certs=true

    # This property is used to select the log level, which controls the amount
    # of information logged on HTTP requests based on the severity of the events.
    # Possible values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL.
    # and see https://quarkus.io/guides/logging for documentation
    quarkus.log.category."org.apache.http".level=INFO
    quarkus.log.level=INFO
    kie.flyway.enabled=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mtv-plan
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: mtv-plan
    sonataflow.org/workflow-app: mtv-plan
    sonataflow.org/workflow-namespace: ""
  name: mtv-plan-props
