apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: rpj
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: rpj
    sonataflow.org/workflow-app: rpj
    sonataflow.org/workflow-namespace: ""
  name: rpj-secrets
stringData:
  NOTIFICATIONS_BEARER_TOKEN: ""
