apiVersion: v1
data:
  application.properties: |
    quarkus.rest-client.patch_k8s_resource_yaml.url=${OCP_URL}
    quarkus.openapi-generator.patch_k8s_resource_yaml.auth.BearerToken.bearer-token=${OCP_TOKEN}
    quarkus.tls.trust-all=true
    quarkus.kubernetes-client.trust-certs=true

    # This property is used to select the log level, which controls the amount
    # of information logged on HTTP requests based on the severity of the events.
    # Possible values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL.
    # and see https://quarkus.io/guides/logging for documentation
    quarkus.log.category."org.apache.http".level=INFO
    quarkus.log.level=INFO
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: patch-k8s-resource
    sonataflow.org/workflow-app: patch-k8s-resource
  name: patch-k8s-resource-props
