apiVersion: v1
kind: Service
metadata:
  name: user-onboarding-server
spec:
  selector:
    app: user-onboarding-server
  ports:
    - protocol: TCP
      port: 8080 # External port
      targetPort: 8080 # Matches the container port
  type: ClusterIP # Use LoadBalancer if exposing externally
