apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: mtv-migration
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: mtv-migration
    sonataflow.org/workflow-app: mtv-migration
    sonataflow.org/workflow-namespace: ""
  name: mtv-migration-secrets
stringData:
  NOTIFICATIONS_BEARER_TOKEN: ""
