apiVersion: v1
data:
  application.properties: |
    # This property is used to select the log level, which controls the amount
    # of information logged on HTTP requests based on the severity of the events.
    # Possible values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL.
    # and see https://quarkus.io/guides/logging for documentation
    quarkus.log.category."org.apache.http".level=DEBUG
    quarkus.log.level=INFO
    quarkus.rest-client.scafolderMock_yaml.url=http://127.0.0.1:8282
    quarkus.rest-client.gitlab_yaml.url=https://gitlab.com/
    quarkus.kogito.devservices.enabled=false
    quarkus.openapi-generator.gitlab_yaml.auth.BearerToken.token-propagation=true
    quarkus.openapi-generator.gitlab_yaml.auth.BearerToken.header-name=X-Authorization-GitLab
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: gl-pr
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: gl-pr
    sonataflow.org/workflow-app: gl-pr
    sonataflow.org/workflow-namespace: ""
  name: gl-pr-props
