apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: gl-pr
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: gl-pr
    sonataflow.org/workflow-app: gl-pr
    sonataflow.org/workflow-namespace: ""
  name: gl-pr-secrets
stringData:
  NOTIFICATIONS_BEARER_TOKEN: ""
