openapi: 3.0.0
info:
  title: Httpbin API
  version: "1.0"
paths:
  /delay/{seconds}:
    get:
      summary: Delays responding for a number of seconds
      operationId: delayCall
      parameters:
        - name: seconds
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Success
  /status/{code}:
    get:
      summary: Returns a given HTTP status code
      operationId: statusCall
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Server Error
