apiVersion: v1
data:
  list-users.json: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "selectUser": {
          "type": "string",
          "title": "Please select a user name from the list",
          "ui:widget": "ActiveDropdown",
          "ui:props": {
            "fetch:url": "$${{backend.baseUrl}}/api/catalog/entities?fields=metadata.name,metadata.namespace,kind&filter=kind=user",
            "fetch:response:value": "[$map($,function($v){$lowercase( $v.kind ) & ':' & $v.metadata.namespace & '/' & $v.metadata.name})]",
            "fetch:response:label": "[$map($,function($v){$lowercase( $v.kind ) & ':' & $v.metadata.namespace & '/' & $v.metadata.name})]",
            "fetch:method": "GET",
            "fetch:headers": {
              "Authorization": "Bearer $${{identityApi.token}}"
            }
          }
        }
      }
    }
  workflow-output-schema.json: |-
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WorkflowResult",
        "description": "Schema of workflow output",
        "type": "object",
        "properties": {
            "result": {
                "$ref": "../shared/schemas/workflow-result-schema.json",
                "type": "object"
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-list-users-resources-schemas
