FLOW_NAME=Test Object Type Support in ui:props
FLOW_SUMMARY=Test Object Type Support in ui:props
FLOW_DESCRIPTION=Testing object type support for fetch:response:* properties in ui:props - RHIDP-11054
