# This property is used to select the log level, which controls the amount
# of information logged on HTTP requests based on the severity of the events.
# Possible values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL.
# and see https://quarkus.io/guides/logging for documentation
quarkus.log.category."org.apache.http".level=DEBUG
quarkus.log.level=DEBUG

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres.showcase.svc.cluster.local:5432/sonata
quarkus.datasource.username=sonata
quarkus.datasource.password=sonata

# Persistence
kogito.persistence.type=jdbc
kogito.persistence.auto.ddl=false
kie.flyway.enabled=true

quarkus.oidc.enabled=false
quarkus.kogito.devservices.enabled=false
quarkus.openapi-generator.github_yaml.auth.BearerToken.token-propagation=true
quarkus.openapi-generator.github_yaml.auth.BearerToken.header-name=X-Authorization-Github
# quarkus.rest-client.github_yaml.headers.Accept=application/vnd.github+json
# quarkus.openapi-generator.github_yaml.auth.BearerToken.header-name=X-Authorization-github
# quarkus.openapi-generator.github_yaml.auth.BearerToken.bearer-token=${ghToken}

# quarkus.openapi-generator.githubtwo_yaml.auth.BearerToken.token-propagation=true
# quarkus.openapi-generator.githubtwo_yaml.auth.BearerToken.header-name=X-Authorization-github-two

quarkus.openapi-generator.gitlab_yaml.auth.BearerToken.token-propagation=true
quarkus.openapi-generator.gitlab_yaml.auth.BearerToken.header-name=X-Authorization-gitlab
